swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /user/:
    post:
      tags:
      - user
      description: create users
      operationId: UserController.新增用户
      parameters:
      - in: formData
        name: nickName
        description: 昵称
        required: true
        type: string
      responses:
        "200":
          description: '{string} success'
        "403":
          description: create users failed
tags:
- name: user
  description: |
    继承apiController
